### ISSUE TITLE
Upload시 403에러 발생하는데 원인 확인 필요

### ISSUE THREAD

**Issue by chani0520** [Seohyung/pickpick_front#46]
게시물 삭제기능 구현후 테스트 단계에서 Upload화면에서 403에러 메세지 발생하여 확인 필요

**Comment by chani0520** [comment]
![image](https://user-images.githubusercontent.com/63958419/156713678-b974432a-0666-4eeb-9d3c-01552b050e6a.png)

**Comment by Seohyung** [comment]
서버가 개발서버 또는 실서버인지에 따라 S3 관련 환경변수가 바뀌도록,

Backend의
1. ./config/index.js 수정
2. .env 파일에 'S3_BUCKETNAME' 변수 추가 : 개발서버는 'pickpick', 실서버는 'pickpics3'
